apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helloworld.fullname" . }}-html-files
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
