apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helloworld.fullname" . }}-html-files
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
data:
  index.html: |
    ConfigMap from helmcreatedemo
