replicas: 1
minimumMasterNodes: 1

ingress:
  enabled: true
  className: public
  hosts:
    - host: elk.microk8s-vm #Change the hostname to the one you need
      paths:
        - path: /
  
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
