apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: kafka-connect
  name: kafka-connect
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka-connect
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-connect
    spec:
      containers:
      - env:
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: 192.168.10.8:9092
        - name: CONNECT_GROUP_ID
          value: "1"
        - name: "CONNECT_CONFIG_STORAGE_TOPIC"
          value: "kafka-connect-config"
        - name: "CONNECT_OFFSET_STORAGE_TOPIC"
          value: "kafka-connect-offset"
        - name: "CONNECT_STATUS_STORAGE_TOPIC"
          value: "kafka-connect-status"
        - name: "CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR"
          value: "1"
        - name: "CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR"
          value: "1"
        - name: "CONNECT_STATUS_STORAGE_REPLICATION_FACTOR"
          value: "1"
        - name: "CONNECT_KEY_CONVERTER"
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: "CONNECT_VALUE_CONVERTER"
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: "CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE"
          value: "false"
        - name: "CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE"
          value: "false"
        - name: "CONNECT_REST_ADVERTISED_HOST_NAME"
          value: "kafka-connect"
        - name: "CONNECT_LOG4J_ROOT_LOGLEVEL"
          value: "TRACE"
        - name: "CONNECT_PLUGIN_PATH"
          value: "/usr/share/confluent-hub-components"
        command:
          - bash
          - -c
          - |
            # Install connector plugins
            # This will by default install into /usr/share/confluent-hub-components/ so make
            #  sure that this path is added to the plugin.path in the environment variables
            confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:latest
            # Launch the Kafka Connect worker
            /etc/confluent/docker/run # &
            # Don't exit
            #sleep infinity
        image: confluentinc/cp-kafka-connect
        imagePullPolicy: Always
        name: connect
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-connect
  name: kafka-connect
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
    nodePort: 30083
  selector:
    app: kafka-connect
  sessionAffinity: None
  type: NodePort
