apiVersion: v1
kind: ConfigMap
metadata:
  name: mskafka-psql-cm
  namespace: store
data:
  init-user-db.sh: |
    #!/bin/bash
    set -e
    
    psql -v ON_ERROR_STOP=0 --username "$POSTGRES_USER" <<-EOSQL
        CREATE DATABASE dbshipping;
        CREATE DATABASE dbinvoicing;
        CREATE DATABASE dborder;
    EOSQL
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        CREATE ROLE $APP_USER LOGIN PASSWORD '$APP_PASSWORD';
        GRANT ALL PRIVILEGES ON DATABASE dbshipping TO "$APP_USER";
        GRANT ALL PRIVILEGES ON DATABASE dbinvoicing TO "$APP_USER";
        GRANT ALL PRIVILEGES ON DATABASE dborder TO "$APP_USER";
    EOSQL
